# Generated by Django 5.2.10 on 2026-04-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BankApp", "0005_alter_userinvestment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="application_fee_code",
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="card_application_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="card_number",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="card_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("blocked", "Blocked"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="card_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="cardholder_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="cvv",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_card_issued",
            field=models.BooleanField(default=False),
        ),
    ]
